map $uri $filename {
    ~*^.*/([^/]+)$ $1;
    default       "";
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen       80;
    server_name  localhost;
    charset utf-8;

    location /dinky/ {
        #根目录位置
        root  /usr/share/nginx/html;
        try_files $uri $uri/ /dinky/index.html;
        #index 文件位置
        index  index.html index.htm;
    }

    location  ~* \.(svg|jpg|jpeg|png|gif|ico)$ {
        root /usr/share/nginx/html;
        # 按顺序尝试以下路径
        try_files $uri /dinky/$filename /dinky/icons/$filename /dinky/imgs/$filename /dinky/static/$filename
        expires 90d;
        access_log off;
    }

    location /dinky/api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8888/api/;
    }

    # WebSocket 代理
    location /api/ws {
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 4s;
        proxy_read_timeout 60s;
        proxy_send_timeout 12s;
    }
}